# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058aea69bb6e02e5bcd0e7fd4935cc48784465b7f0471f22d8f567ca4163488df257a08ed4f5b983aa2adbc5b19950493351cf5c59522720898f0859d2c34752

test:
  secret_key_base: 74c13c96fa646ce5e33d5235f7189f9b4afb4e925723025f5f1358e188513759072194042e8cfde7d10cfc9f0a7e2ff9696d59442da4d1e7f8a745480320be04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
